name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [ 1.17.x, 1.18.x, 1.19.x ]

    name: Go ${{ matrix.go-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run the tests
        run: go test ./... -v
